import json
from datetime import datetime
from pathlib import Path

from critic import CritiqueResult

_BARS = [
    (0.85, "████████████ EXCELLENT"),
    (0.70, "█████████░░░ GOOD"),
    (0.50, "██████░░░░░░ NEEDS REVIEW"),
    (0.25, "███░░░░░░░░░ POOR"),
    (0.00, "█░░░░░░░░░░░ CRITICAL"),
]


def _bar(score: float) -> str:
    for threshold, label in _BARS:
        if score >= threshold:
            return label
    return "░░░░░░░░░░░░ N/A"


def generate_json(critique: CritiqueResult, repo_path: str) -> dict:
    return {
        "meta": {
            "repository": repo_path,
            "generated": datetime.now().isoformat(),
        },
        "precepts": critique.precept_scores,
        "static_analysis": critique.static_findings,
        "vibe_indicators": critique.vibe_indicators,
        "sampled_files": critique.sampled_files,
    }


def generate_markdown(critique: CritiqueResult, repo_path: str) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    sf = critique.static_findings

    md = [
        "# Vibe Coding Critique Report",
        "",
        f"**Repository:** `{repo_path}`  ",
        f"**Date:** {now}",
        "",
        "---",
        "",
        "## Codebase Overview",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Files analyzed | {sf['total_files']} |",
        f"| Total lines | {sf['total_lines']:,} |",
        f"| Languages | {', '.join(sf['languages'].keys()) or 'None detected'} |",
        f"| Test files | {sf['test_files']} ({sf['test_ratio']:.1%}) |",
        f"| Dependency manifests | {', '.join(sf['dependency_files_found']) or 'None found'} |",
        "",
        "---",
        "",
        "## Precept Scores",
        "",
        "| Precept | Score |",
        "|---------|-------|",
    ]

    for data in critique.precept_scores.values():
        md.append(f"| {data['name']} | {data['score']:.2f} |")

    md += ["", "---", "", "## Detailed Findings", ""]

    for data in critique.precept_scores.values():
        score = data["score"]
        md += [
            f"### {data['name']}",
            f"**Score: {score:.2f}** &nbsp; `{_bar(score)}`",
            "",
        ]
        if data.get("issues"):
            md.append("**Issues identified:**")
            for issue in data["issues"]:
                md.append(f"- {issue}")
            md.append("")

        if data.get("file_details"):
            md.append("<details><summary>Per-file breakdown</summary>")
            md += ["", "| File | Score |", "|------|-------|"]
            for fd in data["file_details"]:
                md.append(f"| `{fd['file']}` | {fd['score']:.2f} |")
            md += ["", "</details>", ""]

    md += ["---", "", "## Vibe Coding Risk Assessment", ""]

    if critique.vibe_indicators:
        md.append("**Signals detected:**")
        md.append("")
        for indicator in critique.vibe_indicators:
            md.append(f"- {indicator}")
        md.append("")
    else:
        md += ["No strong vibe coding indicators detected.", ""]

    if sf.get("files_with_secret_patterns"):
        md += [
            "### High Priority — Potential Credential Exposure",
            "",
            "These files contain patterns resembling hardcoded credentials or API keys:",
            "",
        ]
        for f in sf["files_with_secret_patterns"]:
            md.append(f"- `{f}`")
        md.append("")

    if sf.get("high_nesting_files"):
        md += ["### Deep Nesting (>8 levels)", ""]
        for f in sf["high_nesting_files"][:5]:
            md.append(f"- `{f}`")
        md.append("")

    if sf.get("large_files"):
        md += ["### Large Files (>300 lines)", ""]
        for f in sf["large_files"][:5]:
            md.append(f"- `{f}`")
        md.append("")

    md += ["---", "", "## Files Sampled for LLM Analysis", ""]
    for f in critique.sampled_files:
        md.append(f"- `{f}`")

    md += [
        "",
        "---",
        "",
        "*Generated by [vibe-critic](https://github.com/) — "
        "codebase analysis against vibe coding precepts*",
    ]

    return "\n".join(md)


def write_reports(
    critique: CritiqueResult, repo_path: str, output_dir: str = "."
) -> tuple:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    json_path = out / "report.json"
    json_path.write_text(
        json.dumps(generate_json(critique, repo_path), indent=2),
        encoding="utf-8",
    )

    md_path = out / "CRITIQUE.md"
    md_path.write_text(
        generate_markdown(critique, repo_path),
        encoding="utf-8",
    )

    return str(json_path), str(md_path)
